services:
  db:
    image: postgres:15
    container_name: spexs_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: spexs_api
    restart: always
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
  pipeline:
    build: .
    container_name: spexs_pipeline
    env_file: .env
    depends_on:
      - db
    command: ["python", "orchestrator.py"]
    volumes:
      - .:/app
  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.5.0
    volumes:
      - ./dbt_project:/usr/app
      - ./dbt_project/profiles.yml:/root/.dbt/profiles.yml #conection profiles
    working_dir: /usr/app
    env_file: .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_SCHEMA=${DB_SCHEMA:-silver}
    depends_on:
      - db
    profiles: ["tools"] #run only when it's required
    ports:
      - "8080:8080"
volumes:
  postgres_data: